[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "Sequential_Fish"
version = "1.2.2"
authors = [
	{ name="Slimani Floric", email="floric.slimani@live.fr" },
]
description = "Open source package deploying a complete quantification pipeline for analysis of sequential smFish images. Raw data can then be analysed by custom means or with out of the bow analysis pipelined provided."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: BSD License",
	"Operating System :: OS Independent",
]
dependencies = [
"big_fish_reloaded>=0.6.3",
"AF-eraser >= 0.1.0",
"czifile == 2026.8.16",
"magicgui >= 0.10.2",
"matplotlib >= 3.11.2",
"napari[PySide] >= 0.9.1",
"numpy >= 2.5.3",
"pandas >= 3.0.5",
"smfishtools>=0.2.2",
"scikit-image >= 0.26.0",
"scikit-learn>=1.9.1",
"scipy >= 1.18.1",
"tqdm >= 4.70.1",
"pebble",
"openpyxl >= 3.1.5",
"ome_types",
"lxml >= 6.1.3",
"prince >= 0.20.2",
"igraph >= 1.0.0",
"leidenalg >= 0.12.0"
]

[project.urls]
Homepage = "https://github.com/SlimaniF/Sequential_Fish"
Wiki = "https://github.com/SlimaniF/Sequential_Fish/wiki"
Issues = "https://github.com/SlimaniF/Sequential_Fish/issues"
